<?php
/**
 * FlightsFlightStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Flights API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * FlightsFlightStatus Class Doc Comment
 *
 * @category Class
 * @description For customers subscribing to automatic updates, the flight status will be automatically updated. Status is also writable for manual updates.   - UNKNOWN: No status is known, or flight is not yet scheduled.  - SCHEDULED: Flight is scheduled to depart.  - DEPARTED: Flight has left the departure gate, but may not be airborne yet.  - INAIR: Flight is airborne.  - LANDED: Flight has landed, but may not yet be at the arrival gate.  - ARRIVED: Flight has arrived at the destination gate.  - CANCELLED: Flight has been cancelled.  - DELAYED: Flight is delayed to depart by at least 15 minutes.  - DEPARTED_DIVERTED: Flight has been diverted from its scheduled destination and has left the departure gate.  - INAIR_DIVERTED: Flight has been diverted from its scheduled destination and is airborne.  - ARRIVED_DIVERTED: Flight has arrived at a location different to its scheduled destination.  - DEPARTED_RECOVERY: Flight has left its diverted destination en-route to its original destination.  - INAIR_RECOVERY: Flight has left its diverted destination airborne en-route to its original destination.  - ARRIVED_RECOVERY: Flight has landed at is original scheduled destination.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FlightsFlightStatus
{
    /**
     * Possible values of this enum
     */
    const UNKNOWN = 'UNKNOWN';
const SCHEDULED = 'SCHEDULED';
const DEPARTED = 'DEPARTED';
const INAIR = 'INAIR';
const LANDED = 'LANDED';
const ARRIVED = 'ARRIVED';
const CANCELLED = 'CANCELLED';
const DELAYED = 'DELAYED';
const DEPARTED_DIVERTED = 'DEPARTED_DIVERTED';
const INAIR_DIVERTED = 'INAIR_DIVERTED';
const ARRIVED_DIVERTED = 'ARRIVED_DIVERTED';
const DEPARTED_RECOVERY = 'DEPARTED_RECOVERY';
const INAIR_RECOVERY = 'INAIR_RECOVERY';
const ARRIVED_RECOVERY = 'ARRIVED_RECOVERY';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
self::SCHEDULED,
self::DEPARTED,
self::INAIR,
self::LANDED,
self::ARRIVED,
self::CANCELLED,
self::DELAYED,
self::DEPARTED_DIVERTED,
self::INAIR_DIVERTED,
self::ARRIVED_DIVERTED,
self::DEPARTED_RECOVERY,
self::INAIR_RECOVERY,
self::ARRIVED_RECOVERY,        ];
    }
}
