<?php
/**
 * FlightsIDADIndicator
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Flights API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * FlightsIDADIndicator Class Doc Comment
 *
 * @category Class
 * @description Industry Discount / Airline Discount codes. See IATA Recommended Practice 1788.   - NONE: No Industry discount  - IDN1: Industry discount, other carrier employee/all other eligible persons, firm reservation  - IDN2: Industry discount, other carrier employee/all other eligible persons, space available  - IDB1: Industry discount, other carrier employee travelling on duty, firm reservation  - IDB2: Industry discount, other carrier employee travelling on duty, pace available  - AD: Ticket issued pursuant to Resolution 880  - DG: Ticket issued pursuant to Resolution 200g  - DM: Discount not covered by industry regulations (for online use only)  - GE: Ticket issued pursuant to Resolution 886  - IG: Ticket issued pursuant to Resolution 788  - RG: Ticket issued pursuant to Resolution 888  - UD: Ticket issued pursuant to Resolution 884  - ID: Industry discount ticket - no classification designator  - IDFS1: Industry discount, member&#x27;s own employee travelling on duty, firm reservation  - IDFS2: Industry discount, member&#x27;s own employee travelling on duty, space available  - IDR1: Industry discount, member&#x27;s own employee/dependant, firm reservation  - IDR2: Industry discount, member&#x27;s own employee/dependant, space available
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FlightsIDADIndicator
{
    /**
     * Possible values of this enum
     */
    const NONE = 'NONE';
const IDN1 = 'IDN1';
const IDN2 = 'IDN2';
const IDB1 = 'IDB1';
const IDB2 = 'IDB2';
const AD = 'AD';
const DG = 'DG';
const DM = 'DM';
const GE = 'GE';
const IG = 'IG';
const RG = 'RG';
const UD = 'UD';
const ID = 'ID';
const IDFS1 = 'IDFS1';
const IDFS2 = 'IDFS2';
const IDR1 = 'IDR1';
const IDR2 = 'IDR2';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
self::IDN1,
self::IDN2,
self::IDB1,
self::IDB2,
self::AD,
self::DG,
self::DM,
self::GE,
self::IG,
self::RG,
self::UD,
self::ID,
self::IDFS1,
self::IDFS2,
self::IDR1,
self::IDR2,        ];
    }
}
