<?php
/**
 * FlightsIdentityDocument
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Flights API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * FlightsIdentityDocument Class Doc Comment
 *
 * @category Class
 * @description Type of document used to validate the traveler&#x27;s identity.   - PASSPORT: Passport  - NATIONAL_ID_CARD: National ID card  - DRIVING_LICENSE: Driving license  - CREDIT_CARD: Credit card  - FREQUENT_FLYER_CARD: Frequent flyer card  - OTHER_TRAVEL_DOCUMENT: Other travel document
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FlightsIdentityDocument
{
    /**
     * Possible values of this enum
     */
    const PASSPORT = 'PASSPORT';
const NATIONAL_ID_CARD = 'NATIONAL_ID_CARD';
const DRIVING_LICENSE = 'DRIVING_LICENSE';
const CREDIT_CARD = 'CREDIT_CARD';
const FREQUENT_FLYER_CARD = 'FREQUENT_FLYER_CARD';
const OTHER_TRAVEL_DOCUMENT = 'OTHER_TRAVEL_DOCUMENT';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PASSPORT,
self::NATIONAL_ID_CARD,
self::DRIVING_LICENSE,
self::CREDIT_CARD,
self::FREQUENT_FLYER_CARD,
self::OTHER_TRAVEL_DOCUMENT,        ];
    }
}
