<?php
/**
 * FlightsFlightTimes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Flights API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * FlightsFlightTimes Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FlightsFlightTimes implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'flightsFlightTimes';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'scheduled_departure_time' => '\Swagger\Client\Model\IoTime',
'boarding_time' => '\Swagger\Client\Model\IoTime',
'gate_closing_time' => '\Swagger\Client\Model\IoTime',
'scheduled_arrival_time' => '\Swagger\Client\Model\IoTime'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'scheduled_departure_time' => null,
'boarding_time' => null,
'gate_closing_time' => null,
'scheduled_arrival_time' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'scheduled_departure_time' => 'scheduledDepartureTime',
'boarding_time' => 'boardingTime',
'gate_closing_time' => 'gateClosingTime',
'scheduled_arrival_time' => 'scheduledArrivalTime'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'scheduled_departure_time' => 'setScheduledDepartureTime',
'boarding_time' => 'setBoardingTime',
'gate_closing_time' => 'setGateClosingTime',
'scheduled_arrival_time' => 'setScheduledArrivalTime'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'scheduled_departure_time' => 'getScheduledDepartureTime',
'boarding_time' => 'getBoardingTime',
'gate_closing_time' => 'getGateClosingTime',
'scheduled_arrival_time' => 'getScheduledArrivalTime'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['scheduled_departure_time'] = isset($data['scheduled_departure_time']) ? $data['scheduled_departure_time'] : null;
        $this->container['boarding_time'] = isset($data['boarding_time']) ? $data['boarding_time'] : null;
        $this->container['gate_closing_time'] = isset($data['gate_closing_time']) ? $data['gate_closing_time'] : null;
        $this->container['scheduled_arrival_time'] = isset($data['scheduled_arrival_time']) ? $data['scheduled_arrival_time'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets scheduled_departure_time
     *
     * @return \Swagger\Client\Model\IoTime
     */
    public function getScheduledDepartureTime()
    {
        return $this->container['scheduled_departure_time'];
    }

    /**
     * Sets scheduled_departure_time
     *
     * @param \Swagger\Client\Model\IoTime $scheduled_departure_time scheduled_departure_time
     *
     * @return $this
     */
    public function setScheduledDepartureTime($scheduled_departure_time)
    {
        $this->container['scheduled_departure_time'] = $scheduled_departure_time;

        return $this;
    }

    /**
     * Gets boarding_time
     *
     * @return \Swagger\Client\Model\IoTime
     */
    public function getBoardingTime()
    {
        return $this->container['boarding_time'];
    }

    /**
     * Sets boarding_time
     *
     * @param \Swagger\Client\Model\IoTime $boarding_time boarding_time
     *
     * @return $this
     */
    public function setBoardingTime($boarding_time)
    {
        $this->container['boarding_time'] = $boarding_time;

        return $this;
    }

    /**
     * Gets gate_closing_time
     *
     * @return \Swagger\Client\Model\IoTime
     */
    public function getGateClosingTime()
    {
        return $this->container['gate_closing_time'];
    }

    /**
     * Sets gate_closing_time
     *
     * @param \Swagger\Client\Model\IoTime $gate_closing_time gate_closing_time
     *
     * @return $this
     */
    public function setGateClosingTime($gate_closing_time)
    {
        $this->container['gate_closing_time'] = $gate_closing_time;

        return $this;
    }

    /**
     * Gets scheduled_arrival_time
     *
     * @return \Swagger\Client\Model\IoTime
     */
    public function getScheduledArrivalTime()
    {
        return $this->container['scheduled_arrival_time'];
    }

    /**
     * Sets scheduled_arrival_time
     *
     * @param \Swagger\Client\Model\IoTime $scheduled_arrival_time scheduled_arrival_time
     *
     * @return $this
     */
    public function setScheduledArrivalTime($scheduled_arrival_time)
    {
        $this->container['scheduled_arrival_time'] = $scheduled_arrival_time;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
