<?php
/**
 * IoGender
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Flights API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * IoGender Class Doc Comment
 *
 * @category Class
 * @description Gender, as per government issued id.   - NOT_KNOWN: Use only where gender is not known  - MALE: Male  - FEMALE: Female
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IoGender
{
    /**
     * Possible values of this enum
     */
    const NOT_KNOWN = 'NOT_KNOWN';
const MALE = 'MALE';
const FEMALE = 'FEMALE';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NOT_KNOWN,
self::MALE,
self::FEMALE,        ];
    }
}
