<?php
/**
 * IoPassBundle
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Flights API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * IoPassBundle Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IoPassBundle implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ioPassBundle';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
'url' => 'string',
'google_pay_url' => 'string',
'apple_pass_bytes' => 'string',
'multiple_passes_url' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
'url' => null,
'google_pay_url' => null,
'apple_pass_bytes' => 'byte',
'multiple_passes_url' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
'url' => 'url',
'google_pay_url' => 'googlePayURL',
'apple_pass_bytes' => 'applePassBytes',
'multiple_passes_url' => 'multiplePassesURL'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
'url' => 'setUrl',
'google_pay_url' => 'setGooglePayUrl',
'apple_pass_bytes' => 'setApplePassBytes',
'multiple_passes_url' => 'setMultiplePassesUrl'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
'url' => 'getUrl',
'google_pay_url' => 'getGooglePayUrl',
'apple_pass_bytes' => 'getApplePassBytes',
'multiple_passes_url' => 'getMultiplePassesUrl'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['google_pay_url'] = isset($data['google_pay_url']) ? $data['google_pay_url'] : null;
        $this->container['apple_pass_bytes'] = isset($data['apple_pass_bytes']) ? $data['apple_pass_bytes'] : null;
        $this->container['multiple_passes_url'] = isset($data['multiple_passes_url']) ? $data['multiple_passes_url'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id The PassKit Id that uniquely references the pass.
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url The URL to the web landing page.
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets google_pay_url
     *
     * @return string
     */
    public function getGooglePayUrl()
    {
        return $this->container['google_pay_url'];
    }

    /**
     * Sets google_pay_url
     *
     * @param string $google_pay_url A URL that can be used in an Android app or email. Note that this is not recommended for web use.
     *
     * @return $this
     */
    public function setGooglePayUrl($google_pay_url)
    {
        $this->container['google_pay_url'] = $google_pay_url;

        return $this;
    }

    /**
     * Gets apple_pass_bytes
     *
     * @return string
     */
    public function getApplePassBytes()
    {
        return $this->container['apple_pass_bytes'];
    }

    /**
     * Sets apple_pass_bytes
     *
     * @param string $apple_pass_bytes The Base64 encoded bytes of the Apple Wallet pass.
     *
     * @return $this
     */
    public function setApplePassBytes($apple_pass_bytes)
    {
        $this->container['apple_pass_bytes'] = $apple_pass_bytes;

        return $this;
    }

    /**
     * Gets multiple_passes_url
     *
     * @return string
     */
    public function getMultiplePassesUrl()
    {
        return $this->container['multiple_passes_url'];
    }

    /**
     * Sets multiple_passes_url
     *
     * @param string $multiple_passes_url A URL for multiple passes, linked by a common index.
     *
     * @return $this
     */
    public function setMultiplePassesUrl($multiple_passes_url)
    {
        $this->container['multiple_passes_url'] = $multiple_passes_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
