<?php
/**
 * FlightsPassengerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Flights API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FlightsPassengerTest Class Doc Comment
 *
 * @category    Class
 * @description Passenger information can optionally be provided. All fields are optional with the exception of the Passenger name to be rendered on the boarding pass. All passenger is treated as PII and encrypted at rest. Passenger information is deleted or rendered unusable once the pass record has invalidated.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FlightsPassengerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FlightsPassenger"
     */
    public function testFlightsPassenger()
    {
    }

    /**
     * Test attribute "passenger_details"
     */
    public function testPropertyPassengerDetails()
    {
    }

    /**
     * Test attribute "frequent_flyer_info"
     */
    public function testPropertyFrequentFlyerInfo()
    {
    }

    /**
     * Test attribute "identity_details"
     */
    public function testPropertyIdentityDetails()
    {
    }

    /**
     * Test attribute "with_infant"
     */
    public function testPropertyWithInfant()
    {
    }

    /**
     * Test attribute "infant_details"
     */
    public function testPropertyInfantDetails()
    {
    }

    /**
     * Test attribute "known_traveler_number"
     */
    public function testPropertyKnownTravelerNumber()
    {
    }
}
