<?php
/**
 * FlightsSeatClassPolicyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Flights API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FlightsSeatClassPolicyTest Class Doc Comment
 *
 * @category    Class
 * @description The Seat Class Policy is used to determine informational labels on the pass.   - CABIN_BASED: Seats groups are determined by cabin. \&quot;Cabin\&quot; will be used as the label on the pass.  - CLASS_BASED: Seats groups are determined by class of travel. \&quot;Class\&quot; will be used as the label on the pass.  - TIER_BASED: Seat groups are determined by tier. \&quot;Tier\&quot; will be used as the label on the pass.  - SEAT_CLASS_POLICY_OTHER: Another, or no seat policy is in place. No label will be used on the pass.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FlightsSeatClassPolicyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FlightsSeatClassPolicy"
     */
    public function testFlightsSeatClassPolicy()
    {
    }
}
