<?php
/**
 * FlightsBoardingPassRecordRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Flights API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FlightsBoardingPassRecordRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Used to request a digital boarding pass record by ticket number, index or pass id.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FlightsBoardingPassRecordRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FlightsBoardingPassRecordRequest"
     */
    public function testFlightsBoardingPassRecordRequest()
    {
    }

    /**
     * Test attribute "ticket_number"
     */
    public function testPropertyTicketNumber()
    {
    }

    /**
     * Test attribute "index"
     */
    public function testPropertyIndex()
    {
    }

    /**
     * Test attribute "pass_id"
     */
    public function testPropertyPassId()
    {
    }
}
