<?php
/**
 * FlightsCarrierTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Flights API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FlightsCarrierTest Class Doc Comment
 *
 * @category    Class
 * @description A carrier record contains details of the carrier.  The carrier will be the issuer of the boarding pass and may be used as a marketing or operating carrier.  All marketing and operating carriers require a Carrier record.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FlightsCarrierTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FlightsCarrier"
     */
    public function testFlightsCarrier()
    {
    }

    /**
     * Test attribute "iata_carrier_code"
     */
    public function testPropertyIataCarrierCode()
    {
    }

    /**
     * Test attribute "icao_carrier_code"
     */
    public function testPropertyIcaoCarrierCode()
    {
    }

    /**
     * Test attribute "iata_accounting_code"
     */
    public function testPropertyIataAccountingCode()
    {
    }

    /**
     * Test attribute "airline_name"
     */
    public function testPropertyAirlineName()
    {
    }

    /**
     * Test attribute "localized_airline_name"
     */
    public function testPropertyLocalizedAirlineName()
    {
    }

    /**
     * Test attribute "pass_type_identifier"
     */
    public function testPropertyPassTypeIdentifier()
    {
    }

    /**
     * Test attribute "private_key_id"
     */
    public function testPropertyPrivateKeyId()
    {
    }
}
