<?php
/**
 * FlightsConditionalItemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Flights API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FlightsConditionalItemsTest Class Doc Comment
 *
 * @category    Class
 * @description Conditional items for the flight segment as described in IATA PSC Resolution 792.  Note: items supplied or derived through other objects (E.g. Frequent Flyer information) are not supplied here.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FlightsConditionalItemsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FlightsConditionalItems"
     */
    public function testFlightsConditionalItems()
    {
    }

    /**
     * Test attribute "passenger_description"
     */
    public function testPropertyPassengerDescription()
    {
    }

    /**
     * Test attribute "check_in_source"
     */
    public function testPropertyCheckInSource()
    {
    }

    /**
     * Test attribute "boarding_pass_issuance_source"
     */
    public function testPropertyBoardingPassIssuanceSource()
    {
    }

    /**
     * Test attribute "boarding_pass_issue_date"
     */
    public function testPropertyBoardingPassIssueDate()
    {
    }

    /**
     * Test attribute "document_type"
     */
    public function testPropertyDocumentType()
    {
    }

    /**
     * Test attribute "boarding_pass_issuer"
     */
    public function testPropertyBoardingPassIssuer()
    {
    }

    /**
     * Test attribute "baggage_tag_number"
     */
    public function testPropertyBaggageTagNumber()
    {
    }

    /**
     * Test attribute "selectee_indicator"
     */
    public function testPropertySelecteeIndicator()
    {
    }

    /**
     * Test attribute "international_doc_verification"
     */
    public function testPropertyInternationalDocVerification()
    {
    }

    /**
     * Test attribute "idad_indicator"
     */
    public function testPropertyIdadIndicator()
    {
    }

    /**
     * Test attribute "fast_track"
     */
    public function testPropertyFastTrack()
    {
    }
}
