<?php
/**
 * FlightsPassengerStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Flights API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FlightsPassengerStatusTest Class Doc Comment
 *
 * @category    Class
 * @description Passenger Status as detailed in IATA PSC Resolution 792 Attachment &#x27;C&#x27;. Note: all values other than 0 indicate that the passenger has checked in.   - ISSUED_NOT_CHECKED_IN: Ticket issuance/passenger not checked in  - ISSUED_CHECKED_IN: Ticket issuance/passenger checked in  - BAGGAGE_CHECKED_PASSENGER_NOT_CHECKED_IN: Baggage checked - passenger not checked in  - BAGGAGE_CHECKED_PASSENGER_CHECKED_IN: Baggage checked - passenger checked in  - PASSENGER_PASSED_SECURITY_CHECK: Passenger passed security check  - PASSENGER_PASSED_GATE: Passenger passed gate and exit (coupon used)  - TRANSIT: Transit  - STANDBY: Standby. Seat number not printed on boarding pass at time of check in  - BOARDING_DATA_REVALIDATION_DONE: Boarding data re-validation done  - ORIGINAL_BOARDING_LINE_USED_AT_TICKET_ISSUANCE: Original boarding line used at time of ticket issuance  - UP_OR_DOWN_GRADING_REQUIRED: Up or down grading required
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FlightsPassengerStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FlightsPassengerStatus"
     */
    public function testFlightsPassengerStatus()
    {
    }
}
