<?php
/**
 * FlightsIDADIndicatorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Flights API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FlightsIDADIndicatorTest Class Doc Comment
 *
 * @category    Class
 * @description Industry Discount / Airline Discount codes. See IATA Recommended Practice 1788.   - NONE: No Industry discount  - IDN1: Industry discount, other carrier employee/all other eligible persons, firm reservation  - IDN2: Industry discount, other carrier employee/all other eligible persons, space available  - IDB1: Industry discount, other carrier employee travelling on duty, firm reservation  - IDB2: Industry discount, other carrier employee travelling on duty, pace available  - AD: Ticket issued pursuant to Resolution 880  - DG: Ticket issued pursuant to Resolution 200g  - DM: Discount not covered by industry regulations (for online use only)  - GE: Ticket issued pursuant to Resolution 886  - IG: Ticket issued pursuant to Resolution 788  - RG: Ticket issued pursuant to Resolution 888  - UD: Ticket issued pursuant to Resolution 884  - ID: Industry discount ticket - no classification designator  - IDFS1: Industry discount, member&#x27;s own employee travelling on duty, firm reservation  - IDFS2: Industry discount, member&#x27;s own employee travelling on duty, space available  - IDR1: Industry discount, member&#x27;s own employee/dependant, firm reservation  - IDR2: Industry discount, member&#x27;s own employee/dependant, space available
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FlightsIDADIndicatorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FlightsIDADIndicator"
     */
    public function testFlightsIDADIndicator()
    {
    }
}
