<?php
/**
 * IoLifecycleEventsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Flights API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * IoLifecycleEventsTest Class Doc Comment
 *
 * @category    Class
 * @description Statuses of the pass. A pass will collect multiple statuses as it passes through its lifecycle.   - RENDERED: Pass has been created and presented to the user to install.  - INSTALLED_APPLE: Pass has been installed in at least one Apple device.  - INSTALLED_GOOGLE: Pass has been installed in at least one Google Pay account.  - INSTALLED_ANDROID_OTHER: Pass has been installed in at least one Android wallet app.  - UNINSTALLED_APPLE: Pass has been uninstalled from at least one Apple device.  - UNINSTALLED_GOOGLE: Pass has been uninstalled from at least one Google Pay account.  - UNINSTALLED_ANDROID_OTHER: Pass has been uninstalled from at least one Android wallet app.  - APPLE_PASS_CREATED: An Apple pass bundle has been created.  - GOOGLE_PAY_RECORD_CREATED: A Google Pay record has been created.  - INVALIDATE_REQUESTED: Invalidation request sent to pass.  - INVALIDATE_CONFIRMED: Pass has been invalidated.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IoLifecycleEventsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IoLifecycleEvents"
     */
    public function testIoLifecycleEvents()
    {
    }
}
