<?php
/**
 * IoMetadataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Flights API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * IoMetadataTest Class Doc Comment
 *
 * @category    Class
 * @description Additional data relating to the pass. Metadata can be provided with a create pass request. The only writeable field is UTM. All other fields are system generated.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IoMetadataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IoMetadata"
     */
    public function testIoMetadata()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "lifecycle_events"
     */
    public function testPropertyLifecycleEvents()
    {
    }

    /**
     * Test attribute "utm"
     */
    public function testPropertyUtm()
    {
    }

    /**
     * Test attribute "alt_id"
     */
    public function testPropertyAltId()
    {
    }

    /**
     * Test attribute "issue_ip_address"
     */
    public function testPropertyIssueIpAddress()
    {
    }

    /**
     * Test attribute "install_ip_address"
     */
    public function testPropertyInstallIpAddress()
    {
    }

    /**
     * Test attribute "render_location"
     */
    public function testPropertyRenderLocation()
    {
    }

    /**
     * Test attribute "render_ip_address"
     */
    public function testPropertyRenderIpAddress()
    {
    }

    /**
     * Test attribute "install_user_agent"
     */
    public function testPropertyInstallUserAgent()
    {
    }

    /**
     * Test attribute "render_user_agent"
     */
    public function testPropertyRenderUserAgent()
    {
    }

    /**
     * Test attribute "install_device_attributes"
     */
    public function testPropertyInstallDeviceAttributes()
    {
    }

    /**
     * Test attribute "render_device_attributes"
     */
    public function testPropertyRenderDeviceAttributes()
    {
    }

    /**
     * Test attribute "issue_at"
     */
    public function testPropertyIssueAt()
    {
    }

    /**
     * Test attribute "rendered_at"
     */
    public function testPropertyRenderedAt()
    {
    }

    /**
     * Test attribute "first_installed_at"
     */
    public function testPropertyFirstInstalledAt()
    {
    }

    /**
     * Test attribute "last_installed_at"
     */
    public function testPropertyLastInstalledAt()
    {
    }

    /**
     * Test attribute "first_uninstalled_at"
     */
    public function testPropertyFirstUninstalledAt()
    {
    }

    /**
     * Test attribute "last_uninstalled_at"
     */
    public function testPropertyLastUninstalledAt()
    {
    }

    /**
     * Test attribute "invalidated_at"
     */
    public function testPropertyInvalidatedAt()
    {
    }

    /**
     * Test attribute "last_updated_at"
     */
    public function testPropertyLastUpdatedAt()
    {
    }
}
