<?php
/**
 * IoPassBundleFormatTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Flights API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * IoPassBundleFormatTest Class Doc Comment
 *
 * @category    Class
 * @description PassBundleFormat is used to specify which format(s) to provide the pass content.   - PASS_URL: The URL to the web landing page.  - GOOGLE_URL: A URL that can be used in an Android app or email. Note that this is not recommended for web use.  - APPLE_PASS_BUNDLE: The Base64 encoded bytes of the Apple Wallet pass bundle.  - MULTI_LINK: The URL to a landing page for multiple passes containing a common identifier.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IoPassBundleFormatTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IoPassBundleFormat"
     */
    public function testIoPassBundleFormat()
    {
    }
}
