<?php
/**
 * FlightDesignatorsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Flights API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * FlightDesignatorsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FlightDesignatorsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for flightsCreateFlightDesignator
     *
     * Create Flight Designation.
     *
     */
    public function testFlightsCreateFlightDesignator()
    {
    }

    /**
     * Test case for flightsDeleteFlightDesignator
     *
     * Delete Flight Designation.
     *
     */
    public function testFlightsDeleteFlightDesignator()
    {
    }

    /**
     * Test case for flightsGetFlightDesignator
     *
     * Get Flight Designation.
     *
     */
    public function testFlightsGetFlightDesignator()
    {
    }

    /**
     * Test case for flightsUpdateFlightDesignator
     *
     * Update Flight Designation.
     *
     */
    public function testFlightsUpdateFlightDesignator()
    {
    }
}
